# Generated by Django 5.1.3 on 2025-01-18 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_code', models.IntegerField(unique=True)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('college_code', models.IntegerField(unique=True)),
                ('college_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.IntegerField(unique=True)),
                ('subject_name', models.CharField(max_length=100, unique=True)),
                ('credits', models.IntegerField()),
                ('admission_year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_month', models.CharField(max_length=10)),
                ('exam_year', models.IntegerField()),
                ('exam_type', models.CharField(choices=[('REGULAR', 'REGULAR'), ('REPETER', 'REPETER')], max_length=8)),
                ('declaration_date', models.CharField(blank=True, max_length=20, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=9)),
                ('semester', models.CharField(max_length=12)),
                ('admission_year', models.CharField(blank=True, max_length=4)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.branch')),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.collegename')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_no', models.IntegerField()),
                ('exam_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.examdata')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sgpa', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('backlog', models.IntegerField(default=0)),
                ('ufm', models.BooleanField()),
                ('result', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10)),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.studentexam')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spid', models.CharField(max_length=10, unique=True)),
                ('enrollment', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('faculty_name', models.CharField(max_length=100)),
                ('admission_year', models.CharField(blank=True, max_length=4)),
                ('image', models.ImageField(blank=True, default='NULL', null=True, upload_to='images/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.collegename')),
            ],
        ),
        migrations.AddField(
            model_name='studentexam',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.studentinfo'),
        ),
        migrations.CreateModel(
            name='GradeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=5)),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.studentexam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.subject')),
            ],
        ),
    ]
