# Generated by Django 5.1.3 on 2024-11-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_code', models.IntegerField(unique=True)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_month', models.CharField(max_length=10)),
                ('exam_year', models.IntegerField()),
                ('exam_type', models.CharField(choices=[('Regular', 'Regular'), ('Repeater', 'Repeater')], max_length=8)),
                ('semester', models.IntegerField()),
                ('declaration_date', models.DateField()),
                ('academic_year', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.IntegerField(unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BranchSubjectSemester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('is_core', models.BooleanField()),
                ('elective_group', models.CharField(blank=True, choices=[('Professional', 'Professional'), ('Elective', 'Elective')], max_length=50, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.branch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_no', models.IntegerField()),
                ('exam_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.examdata')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sgpa', models.FloatField()),
                ('cgpa', models.FloatField()),
                ('backlog', models.IntegerField()),
                ('ufm', models.BooleanField()),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4)),
                ('exam_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.examdata')),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.studentexam')),
            ],
        ),
        migrations.CreateModel(
            name='GradeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=2)),
                ('subject_bss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.branchsubjectsemester')),
                ('student_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.studentexam')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spid', models.CharField(max_length=10, unique=True)),
                ('enrollment', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('faculty_name', models.CharField(max_length=100)),
                ('college_code', models.IntegerField()),
                ('college_name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.branch')),
            ],
        ),
        migrations.AddField(
            model_name='studentexam',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_system.studentinfo'),
        ),
    ]
