# Generated by Django 5.1.3 on 2025-01-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examdata',
            old_name='college_name',
            new_name='college',
        ),
    ]
