# Generated by Django 5.1.3 on 2025-01-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0002_rename_college_name_examdata_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
