# Generated by Django 5.1.3 on 2024-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0005_alter_studentinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdata',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
