# Generated by Django 5.1.3 on 2024-12-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0007_alter_examdata_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsubjectsemester',
            name='semester',
            field=models.CharField(max_length=12),
        ),
    ]
