# Generated by Django 5.1.3 on 2024-12-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0009_alter_result_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdata',
            name='declaration_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examdata',
            name='exam_type',
            field=models.CharField(choices=[('REGULAR', 'REGULAR'), ('REPETER', 'REPETER')], max_length=8),
        ),
    ]
