# Generated by Django 5.1.3 on 2024-12-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0010_alter_examdata_declaration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='academic_year',
            field=models.CharField(default='2021-2022', max_length=9),
        ),
    ]
