# Generated by Django 5.1.3 on 2024-12-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0012_alter_studentinfo_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='academic_year',
        ),
    ]
