# Generated by Django 5.1.3 on 2025-01-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0013_remove_studentinfo_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsubjectsemester',
            name='elective_group',
            field=models.CharField(blank=True, choices=[('PROFESSIONAL', 'PROFESSIONAL'), ('OPEN', 'OPEN')], max_length=50, null=True),
        ),
    ]
