# Generated by Django 5.1.3 on 2025-01-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0014_alter_branchsubjectsemester_elective_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
