# Generated by Django 5.1.3 on 2025-01-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0015_studentinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedata',
            name='grade',
            field=models.CharField(max_length=5),
        ),
    ]
