# Generated by Django 5.1.3 on 2025-01-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0017_alter_result_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
