# Generated by Django 5.1.3 on 2025-01-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0018_alter_studentinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='image',
            field=models.ImageField(blank=True, default='NULL', null=True, upload_to='images/'),
        ),
    ]
