# Generated by Django 5.0.6 on 2025-01-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0019_alter_studentinfo_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchsubjectsemester',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='branchsubjectsemester',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='admission_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='branchsubjectsemester',
            unique_together={('subject', 'branch', 'semester', 'year')},
        ),
    ]
