# Generated by Django 5.0.6 on 2025-01-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0020_alter_branchsubjectsemester_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchsubjectsemester',
            old_name='year',
            new_name='batch_year',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='year',
            new_name='batch_year',
        ),
        migrations.AlterUniqueTogether(
            name='branchsubjectsemester',
            unique_together={('subject', 'branch', 'semester', 'batch_year')},
        ),
    ]
