# Generated by Django 5.0.6 on 2025-01-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0021_rename_year_branchsubjectsemester_batch_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsubjectsemester',
            name='batch_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='batch_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
