# Generated by Django 5.0.6 on 2025-01-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0022_alter_branchsubjectsemester_batch_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsubjectsemester',
            name='is_core',
            field=models.BooleanField(null=True),
        ),
    ]
