# Generated by Django 5.0.6 on 2025-01-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0023_alter_branchsubjectsemester_is_core'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchsubjectsemester',
            unique_together={('subject', 'branch', 'semester')},
        ),
    ]
