# Generated by Django 5.0.6 on 2025-01-13 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0024_alter_branchsubjectsemester_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branchsubjectsemester',
            unique_together={('subject', 'branch', 'semester', 'batch_year')},
        ),
    ]
